name: CI for MWAA Staging

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    branches:
      - '!main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:


#    - uses: actions/checkout@main
#      with:
#        fetch-depth: 0

   # - name: Identify diffed SQL files
      # - git diff main --name-only
      # - change spaces into new lines
      # - remove lines not containing .sql 
      # - remove dags/ prefix and .sql suffix
   #   run: echo "forestfires\nbears\nsquirrels"  > ./git-diff.txt

    - name: Test output
      run: echo "$(cat ./git-diff.txt)"